name: Test and release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-release:
    uses: zifeo/workflows/.github/workflows/py-test-release.yml@main
    with:
      python-matrix: '["3.9", "3.10", "3.11", "3.12"]'
      poetry-version: "1.7.1"
      python-version: "3.10"
      publish-pypi: true
    secrets:
      pypi-token: ${{ secrets.PYPI_TOKEN }}
